# fly.toml app configuration file generated for market-watch-demo on 2026-02-13T23:54:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'market-watch-demo'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
